### PR TITLE
some little fixed

### PR DESCRIPTION
**Pull request by king0billy**
1.add pinned & grouped support(only locale in en & zh-CN)
2. update Manifest to V3.

### CODE REVIEW

**Comment by king0billy** [comment]
after update Manifest to V3,  alert() cannot work. I am fixing.

**Comment by fernandodilland** [comment]
Thank you! I have struggled with V3 😅

**Comment by fernandodilland** [comment]
Thank you! I have struggled with V3 😅

**Comment by king0billy** [comment]
The alart function works properly in V3 now!

I intend to develop features: 

1. The numbers of the total tabs, pinned tabs, and Groups display in options.html
2. function to set limits of pinned tabs and groups.

**Comment by king0billy** [comment]
you 

> 1.add pinned & grouped support(only locale in en & zh-CN)1.添加固定和分组支持（仅限 en 和 zh-CN 中的语言环境） 2. update Manifest to V3.2. 将 Manifest 更新为 V3。

It would be better if you could add localization in other languages and change all "chrome." to "browser.".

**Pull request merged**
